### ISSUE TITLE
Found error and loop restart

### ISSUE THREAD

**Issue by cyztalzboyz** [pratomrerk/slip-verification#2]
slip-verification    | Traceback (most recent call last):
slip-verification    |   File "/app/app.py", line 7, in <module>
slip-verification    |     from models.slip import slip
slip-verification    |   File "/app/models/slip.py", line 2, in <module>
slip-verification    |     import cv2
slip-verification    |   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
slip-verification    |     bootstrap()
slip-verification    |   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
slip-verification    |     native_module = importlib.import_module("cv2")
slip-verification    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
slip-verification    |     return _bootstrap._gcd_import(name[level:], package, level)
slip-verification    | ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by pratomrerk** [comment]
Thank you for your interest in my script.

It's a problem that installing "opencv-python"
Please use the command pip3 install -r requirements.txt
